name: CI Workflow

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: |
            -v ./...
  test:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        go-version: ['1.20', '1.21.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: go get -v ./...

      - name: Run tests
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-test-results-${{ matrix.go-version }}
          path: coverage.out
